import {parse,serialize} from './format.js';
import {chordParts,insertChord} from './chords.js';
import {transliterate} from './transliterate.js';
const englishPanel=document.createElement('section');englishPanel.className='block';englishPanel.innerHTML='<h2>English transliteration</h2><p class="hint">Generated from Telugu. Review the spelling before publishing. Your edits stay until you choose Regenerate.</p><label>English title<input id="english-title"></label><label>English lyrics<textarea id="english-body"></textarea></label><button id="regenerate">Regenerate English</button>';
document.querySelector('.editor').append(englishPanel);
let englishEdited=false;
function syncEnglish(){if(!englishEdited){document.getElementById('english-title').value=transliterate(document.getElementById('title').value);document.getElementById('english-body').value=transliterate(serialize(blocks,false,true));}}
const chordStyles=document.createElement('link');chordStyles.rel='stylesheet';chordStyles.href=new URL('./chords.css',import.meta.url).href;document.head.append(chordStyles);
function chordVerse(text){const verse=element('div',null,'verse');for(const line of text.split('\n')){const row=element('div',null,'chord-line');for(const part of chordParts(line)){const span=element('span',null,'chord-part');span.append(element('span',part.chord||'\u00a0','chord-name'),element('span',part.text||'\u00a0'));row.append(span);}verse.append(row);}return verse;}
const $=id=>document.getElementById(id); let blocks=[]; const key='praise-song-studio-v1';
const mobileStyles=document.createElement('link');mobileStyles.rel='stylesheet';mobileStyles.href=new URL('./mobile.css',import.meta.url).href;document.head.append(mobileStyles);
document.querySelector('.editor').id='editor';document.querySelector('.preview-panel').id='preview-panel';
const jumps=document.createElement('nav');jumps.className='jump-links';jumps.setAttribute('aria-label','Editor navigation');jumps.innerHTML='<a href="#editor">Edit lyrics</a><a href="#preview-panel">Preview & export</a>';document.querySelector('.workspace').before(jumps);
for(const heading of document.querySelectorAll('.panel-heading h2')){heading.textContent=heading.querySelector('span').textContent;}
function message(text){$('message').textContent=text;}
function save(){syncEnglish();try{localStorage.setItem(key,JSON.stringify({title:$('title').value,source:$('source').value,blocks,englishTitle:$('english-title').value,englishBody:$('english-body').value,englishEdited}));$('saved').textContent=englishEdited?'Draft saved · English edits preserved; review after lyric changes':'Draft saved in this browser';}catch{$('saved').textContent='Storage unavailable. Download your draft to keep it.';}}
function element(tag,text,cls){const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;}
function preview(){const target=$('preview');target.replaceChildren();if(!blocks.length){target.append(element('p','Paste your lyrics and choose Arrange lyrics.','hint'));}for(const b of blocks){if('cue'in b){target.append(element('div',b.cue,'badge'));continue;}if(b.label)target.append(element('div',b.label,'section-label'));for(let i=0;i<($('expanded').checked?b.count:1);i++)target.append(chordVerse(b.text));if(b.count>1&&!$('expanded').checked)target.append(element('span',`×${b.count}`,'badge'));}for(const id of ['copy','download'])$(id).disabled=!blocks.length;}
function render(){const list=$('blocks');list.replaceChildren();blocks.forEach((b,index)=>{const card=element('div',null,'block');const tools=element('div',null,'tools');if(!('cue'in b)){const label=element('label','Section');const select=element('select');for(const name of ['', 'Verse','Verse 1','Verse 2','Verse 3','Chorus','Pre-Chorus','Bridge','Ending']){const option=element('option',name||'Unlabelled phrase');option.value=name;select.append(option);}if(![...select.options].some(o=>o.value===b.label)){const option=element('option',b.label);option.value=b.label;select.append(option);}select.value=b.label;select.onchange=()=>{b.label=select.value;save();preview();};label.append(select);tools.append(label);const countLabel=element('label','Times sung');const count=element('select');for(let i=1;i<=12;i++){const o=element('option',`${i}×`);o.value=i;count.append(o);}count.value=b.count;count.onchange=()=>{b.count=Number(count.value);save();render();};countLabel.append(count);tools.append(countLabel);}else tools.append(element('strong','Return cue'));
for(const [text,action] of [['↑',()=>{if(index){[blocks[index-1],blocks[index]]=[blocks[index],blocks[index-1]];}}],['↓',()=>{if(index<blocks.length-1){[blocks[index+1],blocks[index]]=[blocks[index],blocks[index+1]];}}],['Remove',()=>{if(confirm('Remove this phrase from the arranged lyrics?'))blocks.splice(index,1);} ]]){const button=element('button',text);button.setAttribute('aria-label',text==='↑'?'Move phrase up':text==='↓'?'Move phrase down':text);button.onclick=()=>{action();save();render();};tools.append(button);}card.append(tools);const input=element('textarea');input.value=b.cue??b.text;input.setAttribute('aria-label','cue'in b?'Return cue':'Phrase lyrics');input.oninput=()=>{if('cue'in b)b.cue=input.value;else b.text=input.value;save();preview();};card.append(input);
if(!('cue'in b)){
const chordTools=element('div',null,'chord-tools');const chordInput=element('input');chordInput.placeholder='D, Em, G/B…';chordInput.setAttribute('aria-label','Chord symbol');const addChord=element('button','Add chord at cursor');addChord.onclick=()=>{try{b.text=insertChord(input.value,input.selectionStart,chordInput.value.trim());input.value=b.text;save();preview();message('Chord added. Edit or delete its [marker] to change it.');}catch(e){message(e.message);}};chordTools.append(chordInput,addChord);card.append(chordTools,element('p','Place the cursor before a word or syllable, then add a chord. You can also type [D] directly.','hint'));
const split=element('button','Split at cursor');split.onclick=()=>{const p=input.selectionStart;const start=input.value.lastIndexOf('\n',p-1)+1;if(!start||start>=input.value.length){message('Place the cursor on the first line of the new phrase.');return;}const rest=input.value.slice(start);b.text=input.value.slice(0,start).trimEnd();const count=b.count;b.count=1;blocks.splice(index+1,0,{label:'',text:rest,count});save();render();};card.append(split);if(b.count>1)card.append(element('p','Check this group: all its lines are sung '+b.count+' times. Split before the last line if only that line repeats.','hint'));}list.append(card);});$('add').hidden=!blocks.length;preview();}
$('format').onclick=()=>{if(blocks.length&&!confirm('Rebuild the arrangement from the original text? Current phrase edits will be replaced.'))return;try{const next=parse($('source').value);if(!next.length)throw Error('Paste a few lyric lines first.');blocks=next;save();render();message('Arranged. Check the repeat groups, then copy or download.');}catch(e){message(e.message);}};
$('expanded').onchange=preview;for(const id of ['title','source'])$(id).oninput=save;
$('add').onclick=()=>{blocks.push({label:'',text:'',count:1});save();render();};
$('new').onclick=()=>{if(confirm('Start a new song? Download this draft first if you want to keep it.')){blocks=[];$('title').value='';$('source').value='';save();render();message('Ready for a new song.');}};
$('sample').onclick=()=>{if(($('source').value||blocks.length)&&!confirm('Replace this draft with the example?'))return;$('title').value='అన్ని వేళల ఆరాధన';$('source').value='పల్లవి\nఅన్ని వేళల ఆరాధన\nకన్న తండ్రి నీకే మహిమ (4)';blocks=parse($('source').value);save();render();};
function output(){syncEnglish();return $('output').value==='english'?$('english-body').value:$('output').value==='json'?JSON.stringify({title:$('title').value,english_title:$('english-title').value,original_song:$('source').value,normalized_song:serialize(blocks),structured_song:serialize(blocks,true),chord_chart:serialize(blocks,false,true),english_body:serialize(parse($('english-body').value)),structured_english_song:serialize(parse($('english-body').value),true),english_chord_chart:$('english-body').value,status:'draft'},null,2):serialize(blocks,$('output').value==='structured',$('output').value==='chords');}
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(output());message('Copied. Ready to paste into your sheet or app.');}catch{message('Clipboard unavailable. Use Download instead.');}};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([output()],{type:'text/plain;charset=utf-8'}));const link=element('a');link.href=url;link.download=($('title').value||'song').replace(/[<>:"/\\|?*]/g,'-')+($('output').value==='json'?'.json':'.txt');link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const chordOption=element('option','Chord chart');chordOption.value='chords';$('output').append(chordOption);
const englishOption=element('option','English transliteration');englishOption.value='english';$('output').append(englishOption);
for(const id of ['new','sample']){const action=$(id).onclick;$(id).onclick=()=>{const oldBlocks=blocks;action();if(oldBlocks!==blocks){englishEdited=false;save();}};}
for(const id of ['english-title','english-body'])$(id).oninput=()=>{englishEdited=true;save();};
$('regenerate').onclick=()=>{if(englishEdited&&!confirm('Replace your English edits with a fresh transliteration?'))return;englishEdited=false;save();};
try{const previous=JSON.parse(localStorage.getItem(key));if(previous?.englishEdited){englishEdited=true;$('english-title').value=previous.englishTitle||'';$('english-body').value=previous.englishBody||'';}}catch{}
window.addEventListener('load',syncEnglish);
try{const draft=JSON.parse(localStorage.getItem(key));if(draft&&Array.isArray(draft.blocks)&&draft.blocks.every(b=>b&&('cue'in b?typeof b.cue==='string':typeof b.text==='string'&&typeof b.label==='string'&&Number.isInteger(b.count)&&b.count>=1&&b.count<=12))){$('title').value=draft.title||'';$('source').value=draft.source||'';blocks=draft.blocks;}}catch{message('Could not restore the saved draft. You can start a new one.');}render();
