const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const KEYS=['C','C#','Db','D','D#','Eb','E','F','F#','Gb','G','G#','Ab','A','A#','Bb','B'];
const ids=['title','language','key','bpm','meter','tempo','capo','shape','theme','author','maleReference','femaleReference','lyrics','transliteration'];
const map={
'అ':'a','ఆ':'aa','ఇ':'i','ఈ':'ee','ఉ':'u','ఊ':'oo','ఋ':'ru','ఎ':'e','ఏ':'ae','ఐ':'ai','ఒ':'o','ఓ':'oa','ఔ':'au',
'క':'ka','ఖ':'kha','గ':'ga','ఘ':'gha','ఙ':'nga','చ':'cha','ఛ':'chha','జ':'ja','ఝ':'jha','ఞ':'nya','ట':'ta','ఠ':'tha','డ':'da','ఢ':'dha','ణ':'na','త':'tha','థ':'thha','ద':'dha','ధ':'dhha','న':'na','ప':'pa','ఫ':'pha','బ':'ba','భ':'bha','మ':'ma','య':'ya','ర':'ra','ల':'la','వ':'va','శ':'sha','ష':'sha','స':'sa','హ':'ha','ళ':'la','ఱ':'ra',
'ా':'a','ి':'i','ీ':'ee','ు':'u','ూ':'oo','ృ':'ru','ె':'e','ే':'ae','ై':'ai','ొ':'o','ో':'oa','ౌ':'au','ం':'m','ః':'h','్':''};
function transliterateText(text){let out='';for(let i=0;i<text.length;i++){const c=text[i];if(c==='['){const j=text.indexOf(']',i);if(j>-1){out+=text.slice(i,j+1);i=j;continue}}let t=map[c];if(t===undefined){out+=c;continue}if(/[క-హళఱ]/.test(c)&&text[i+1]&&/[ా-ౌ్]/.test(text[i+1])){out+=t.slice(0,-1)}else out+=t}return out.replace(/ {2,}/g,' ')}
function normalizeSections(text){let lines=text.replace(/\r/g,'').split('\n');let verse=0;return lines.map(line=>{let s=line.trim();if(!s)return '';const known=s.match(/^\[?(verse|chorus|bridge|pre[- ]?chorus|intro|outro|tag)(?:\s*(\d+))?\]?:?$/i);if(known){let n=known[1].toLowerCase().replace('pre chorus','pre-chorus');if(n==='verse'&&!known[2])verse++;return `[${n.replace(/\b\w/g,c=>c.toUpperCase())}${known[2]?' '+known[2]:n==='verse'?' '+verse:''}]`}if(/^పల్లవి[:：]?$/i.test(s))return '[Chorus]';if(/^చరణం\s*(\d+)?[:：]?$/i.test(s)){verse++;return `[Verse ${RegExp.$1||verse}]`}return line.replace(/\s+$/,'')}).join('\n').replace(/\n{3,}/g,'\n\n')}
function sections(text){let current={type:'Verse',label:'Verse 1',lines:[]},result=[];text.split('\n').forEach(line=>{const m=line.trim().match(/^\[([^\]]+)\]$/);if(m){if(current.lines.some(x=>x.trim()))result.push(current);current={type:m[1].replace(/\s+\d+$/,''),label:m[1],lines:[]}}else current.lines.push(line)});if(current.lines.some(x=>x.trim()))result.push(current);return result.map((s,index)=>({...s,index,chordLines:s.lines.map((line,lineIndex)=>({lineIndex,text:line.replace(/\[[^\]]+\]/g,''),anchors:[...line.matchAll(/\[([^\]]+)\]/g)].map(m=>({chord:m[1],charIndex:m.index-line.slice(0,m.index).match(/\[[^\]]+\]/g)?.join('').length||m.index}))}))}))}
function song(){return{schemaVersion:1,id:slug($('#title').value)||'untitled-song',title:$('#title').value,language:$('#language').value,music:{key:$('#key').value,bpm:Number($('#bpm').value)||null,timeSignature:$('#meter').value,tempo:$('#tempo').value,capo:Number($('#capo').value)||0,shape:$('#shape').value},tags:$('#theme').value.split(',').map(x=>x.trim()).filter(Boolean),credits:{writer:$('#author').value},references:{maleVoiceYouTube:$('#maleReference').value,femaleVoiceYouTube:$('#femaleReference').value},lyrics:{original:sections($('#lyrics').value),transliteration:sections($('#transliteration').value)},source:{original:$('#lyrics').value,transliteration:$('#transliteration').value}}}
function slug(v){return v.toLowerCase().trim().replace(/[^a-z0-9\u0C00-\u0C7F]+/g,'-').replace(/^-|-$/g,'')}
function render(text){return esc(text).replace(/^\[([^\]]+)\]$/gm,'<span class="section-title">$1</span>').replace(/\[([^\]]+)\]/g,'<span class="chord">$1</span>')}
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function update(){const data=song();$('#json-output').textContent=JSON.stringify(data,null,2);$('#original-preview').innerHTML=render($('#lyrics').value);$('#translit-preview').innerHTML=render($('#transliteration').value);localStorage.setItem('praise-song-studio',JSON.stringify(Object.fromEntries(ids.map(id=>[id,$('#'+id).value]))));$('#save-state').textContent='Saved locally'}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
$('#key').innerHTML=KEYS.map(k=>`<option ${k==='G'?'selected':''}>${k}</option>`).join('');$('#shape').innerHTML=KEYS.map(k=>`<option ${k==='G'?'selected':''}>${k}</option>`).join('');
$$('input,select,textarea').forEach(el=>el.addEventListener('input',()=>{$('#save-state').textContent='Saving…';update()}));
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+btn.dataset.view+'-view').classList.add('active');update()});
$('#format').onclick=()=>{$('#lyrics').value=normalizeSections($('#lyrics').value);update();toast('Sections formatted')};
$('#transliterate').onclick=()=>{$('#transliteration').value=transliterateText($('#lyrics').value);$('#translit-state').textContent='Generated · editable';update();toast('Transliteration generated')};
$('#add-chord').onclick=()=>{$('#chord-pop').hidden=false;$('#chord-input').focus()};
$('#insert-chord').onclick=()=>{const a=$('#lyrics'),ch=$('#chord-input').value.trim();if(!ch)return;const pos=a.selectionStart;a.value=a.value.slice(0,pos)+`[${ch}]`+a.value.slice(pos);a.focus();a.selectionStart=a.selectionEnd=pos+ch.length+2;$('#chord-pop').hidden=true;$('#chord-input').value='';update()};
$('#chord-input').addEventListener('keydown',e=>{if(e.key==='Enter')$('#insert-chord').click();if(e.key==='Escape')$('#chord-pop').hidden=true});
$('#sample').onclick=()=>{$('#title').value='యేసయ్య నీ ప్రేమ';$('#bpm').value='72';$('#meter').value='6/8';$('#tempo').value='Slow';$('#theme').value='Worship, Love, Prayer';$('#lyrics').value='[Verse 1]\n[G]యేసయ్య నీ [C]ప్రేమ\n[D]ఎంతో మధు[G]రము\n\n[Chorus]\n[Em]నీ కృప చా[C]లును\n[D]నా జీవి[G]తము';update();toast('Sample loaded')};
$('#copy-json').onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(song(),null,2));toast('JSON copied')};
$('#export-song').onclick=()=>{const blob=new Blob([JSON.stringify(song(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(slug($('#title').value)||'song')+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#new-song').onclick=()=>{if(!confirm('Clear this song and start a new one?'))return;ids.forEach(id=>$('#'+id).value='');$('#language').value='te';$('#key').value='G';$('#shape').value='G';$('#meter').value='4/4';$('#tempo').value='Medium';$('#capo').value='0';update()};
try{const saved=JSON.parse(localStorage.getItem('praise-song-studio'));if(saved){ids.forEach(id=>{if(saved[id]!==undefined)$('#'+id).value=saved[id]});if(saved.reference&&!saved.maleReference)$('#maleReference').value=saved.reference}}catch{}update();
